version: '2'

services:
  app:
    build: .
    image:  katharostech/quasar-cli:latest
    command: sh
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - 8080:8080
    tty: true
